/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entities.Category;
import javax.swing.JOptionPane;
import model.CategoryDAO;

/**
 *
 * @author junio
 */
public class NewItem extends javax.swing.JFrame {
    
    
    private Category category = new Category();
    private CategoryList viewList;

    /**
     * Creates new form NewItem
     */
    public NewItem(CategoryList viewList) {
        initComponents();
        this.viewList = viewList;
    }
    
    public void setCategory (Category category) {
        this.category = category;
        txtCategory.setText(category.getName());
        if (category.getType() == 'F') {
            jRButnFilm.setSelected(true);
        } else if(category.getType() == 'G') {
            jRBtnGame.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gRBType = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRButnFilm = new javax.swing.JRadioButton();
        jRBtnGame = new javax.swing.JRadioButton();
        txtCategory = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Category");

        gRBType.add(jRButnFilm);
        jRButnFilm.setText("Film");

        gRBType.add(jRBtnGame);
        jRBtnGame.setText("Game");

        txtCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoryActionPerformed(evt);
            }
        });

        jLabel2.setText("Type");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRButnFilm)
                        .addGap(63, 63, 63)
                        .addComponent(jRBtnGame))
                    .addComponent(jLabel1)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRButnFilm)
                    .addComponent(jRBtnGame))
                .addGap(42, 42, 42)
                .addComponent(btnSave)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryActionPerformed
        // TODO add your handling code here:
        
       
        
    }//GEN-LAST:event_txtCategoryActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
 
        category.setName(txtCategory.getText());
        if(jRButnFilm.isSelected()){
               category.setType('F');
               
        }else if (jRBtnGame.isSelected()){
            category.setType('G');
            
        }
        if (category.getType() != ' '){
            
            if(category.getId() == 0) {
                insert();
            } else {
                change();
            }
            
        }else {
            JOptionPane.showMessageDialog(this, "Select the category type");
        }
        
        
    }//GEN-LAST:event_btnSaveActionPerformed
    
      private void insert() {
          if(CategoryDAO.insert(category)){
                JOptionPane.showMessageDialog(this, "New category added successfully!");
                viewList.gettingCategoryList();
                dispose(); /* To close the NewItem screen*/
            }else {
                JOptionPane.showMessageDialog(this, "Error to add the new category");
            }
      }
    
      
      private void change() {
          if(CategoryDAO.change(category)){
                JOptionPane.showMessageDialog(this, "New category changed successfully!");
                viewList.gettingCategoryList();
                dispose(); /* To close the NewItem screen*/
            }else {
                JOptionPane.showMessageDialog(this, "Error to change the new category");
            }
      }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup gRBType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRBtnGame;
    private javax.swing.JRadioButton jRButnFilm;
    private javax.swing.JTextField txtCategory;
    // End of variables declaration//GEN-END:variables
}
